name: Node.js CI

on:
  schedule:
    - cron: '5 9 * * 5'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        bullmq-version: [2.x, 3.x, 4.x, latest]
    services:
      redis:
        image: redis:alpine
        ports:
          - '6379:6379'
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm install bullmq@${{ matrix.bullmq-version }}
      - run: npm run compile
      - run: npm run lint
      - run: npm test
